### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aResonance** [Ridanisaurus/EmendatusEnigmatica#212] opened 2023-09-04 17:04 UTC
### Issue description

hello, how long to wait for a fix for a crash with an error java.lang.NullPointerException: Registry Object not present: emendatusenigmatica:dimensional_block? 

Exactly the same error was in the previous version of the mod with hammer

java.lang.NullPointerException: Registry Object not present: emendatusenigmatica:dimensional_block
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.2.23-universal.jar%231202!/:?] {re:mixin,re:classloading}
	at com.ridanisaurus.emendatusenigmatica.datagen.LangGen.addTranslations(LangGen.java:60) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23831!/:2.1.5-build.61+mc1.19.2] {re:classloading}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.EELangProvider.m_213708_(EELangProvider.java:65) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23831!/:2.1.5-build.61+mc1.19.2] {re:classloading}
	at net.minecraft.data.DataGenerator.m_123917_(DataGenerator.java:57) ~[client-1.19.2-20220805.130853-srg.jar%231197!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at com.ridanisaurus.emendatusenigmatica.EmendatusEnigmatica.generate(EmendatusEnigmatica.java:121) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23831!/:2.1.5-build.61+mc1.19.2] {re:classloading}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.GeneratedPack.<init>(GeneratedPack.java:50) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23831!/:2.1.5-build.61+mc1.19.2] {re:classloading}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.EEPackFinder.lambda$loadPacks$0(EEPackFinder.java:48) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23831!/:2.1.5-build.61+mc1.19.2] {re:classloading}
	at net.minecraft.server.packs.repository.Pack.m_10430_(Pack.java:35) ~[client-1.19.2-20220805.130853-srg.jar%231197!/:?] {re:classloading}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.EEPackFinder.m_7686_(EEPackFinder.java:47) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23831!/:2.1.5-build.61+mc1.19.2] {re:classloading}

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.23

### Emendatus Enigmatica version

2.1.x (Latest)

**Comment by Ridanisaurus** [comment] 2024-01-08 03:07
Duplicate of #202

**Closed as completed by Ridanisaurus** 2024-01-08 03:07 UTC
Labels: bug, duplicate
