### ISSUE TITLE
IE Compat

### ISSUE THREAD

**Issue by FooterManDev** [Ridanisaurus/EmendatusEnigmatica#193] opened 2023-02-21 16:13 UTC
### Describe the feature you'd like

Add Immersive Engineering Compatibility.
Unsure if this would be added with #168, so I apologize if this is a duplicate.

**Comment by Ridanisaurus** [comment] 2023-02-22 09:37
This is indeed a duplicate of #168 which is in the works.

**Closed as completed by Ridanisaurus** 2023-02-22 09:37 UTC
Labels: duplicate, feature request
