### ISSUE TITLE
Xray bug

### ISSUE THREAD

**Issue by mtjohnson47** [Ridanisaurus/EmendatusEnigmatica#103] opened 2021-08-08 02:33 UTC
**Mod Version**
1.16.5-1.2.9

**Describe the bug/enhancement**
Ore variants have xray of liquids and other ores

**To Reproduce - if applicable**
1. Go into a cave in a large cave system with a lot of caves in all directions
2. Look at a custom ore

**Expected behavior**
Ores should be solid, not see-through

**Screenshots**
![image](https://user-images.githubusercontent.com/5100948/128618691-d614c509-d063-42d0-9740-96b62a843d3c.png)

**Additional context**
My hardware is an i5-750, GTX 1070.  This happens on Enigmatica 6 with the Fabulous graphics setting enabled.  It does not happen on Fast or Fancy.  It does not happen with vanilla ores.

**Logs**
latest.log is far too large for pastebin, I uploaded it to my website: https://www.mikemk.net/temp/latest.log

**Comment by Ridanisaurus** [comment] 2021-08-08 11:53
Duplicate of #73

**Closed as completed by Ridanisaurus** 2021-08-08 11:53 UTC
Labels: wontfix
