### ISSUE TITLE
EE Covers Crash Logs

### ISSUE THREAD

**Issue by FooterManDev** [Ridanisaurus/EmendatusEnigmatica#207] opened 2023-07-22 12:58 UTC
### Issue description

While EE is active, if you crash (depending on the crash) you will be shown with this error:
```
java.lang.NullPointerException: Registry Object not present: emendatusenigmatica:some_ee_item
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
```
While in reality, this crash was caused by pressing `Alt` + `F4`, on purpose.
This was also the case for a KubeJS error back awhile ago, EE kept covering up the actual error forcing me to turn it off to get the real error.

### Steps to reproduce

* Install EE, and optionally KubeJS.
* Make a material file.
* Start the game, and attempt to press `Alt` + `F4` as soon as the window appears.
* Error should show.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.21

### Emendatus Enigmatica version

2.1.x (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/FooterMan15/ae51b05dbebd88d70814d3eaeda01c3f

**Comment by Ridanisaurus** [comment] 2023-07-24 07:21
Duplicate of #202

**Closed as completed by Ridanisaurus** 2023-07-24 07:21 UTC
Labels: bug, duplicate
