### ISSUE TITLE
emendatusenigmatica:dimensional_block

### ISSUE THREAD

**Issue by QueenReaperTV** [Ridanisaurus/EmendatusEnigmatica#220] opened 2024-04-30 01:52 UTC
### Issue description

Trying to launch my game and I am getting a game chrash with the message: 
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: emendatusenigmatica:dimensional_block

### Steps to reproduce

Opening Curse Forge
Launch Enigmatica 9
Launch game
Game crashes

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Emendatus Enigmatica version

Current Dev Branch (Manually Compiled)

**Comment by Ridanisaurus** [comment] 2024-07-01 00:14
Duplicate of #202

**Closed as completed by Ridanisaurus** 2024-07-01 00:14 UTC
Labels: bug, to be reviewed
