### ISSUE TITLE
Qustion about the tinting system

### ISSUE THREAD

**Issue by CapturedCherry** [Ridanisaurus/EmendatusEnigmatica#161] opened 2022-11-29 02:34 UTC
### Issue description

Long story short I have been working on a plugin and play set of scripts to simpfiy both modpack devs and players lifes. Because of this I have noticed that the colours on blocks for example have been looking a bit off. So I coyped the example configs and noiced that for example iron block looks a bit off compared to the version in the resources you offer. I'm not sure if this is a bug or me not understanding how the tint system takes hex codes and colours items. So is this a bug? If not then what is the math behind the system ty

![Iron block using example config](https://user-images.githubusercontent.com/110157750/204424599-28ee6d87-511a-4bf4-b2c5-a3bae3e31047.png)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.57

### Emendatus Enigmatica version

2.0.x (Latest)

**Comment by Ridanisaurus** [comment] 2022-11-29 10:24
It is simply impossible to create a tint-based texture as good as a fully drawn graphical texture, there is are multiple limitations such as that Minecraft does not accept any model file that has more than 5 layers, which did limit me to 5 colors instead of the 7-9 colors which is the standard for Minecraft textures.
This is preciously why I provided graphical textures for both Vanilla, and the most common materials in modded.
That said, I did update the templates for the Vanilla materials with new `materialColor` that is a little closer to the original materials, but like I said, it's simply impossible to make them a 100%.
The logic for the hue shifting I used for the tint system can be found here: https://github.com/Ridanisaurus/EmendatusEnigmatica/blob/EEV2-1.19/src/main/java/com/ridanisaurus/emendatusenigmatica/util/ColorHelper.java#L186-L252

This item will be closed as it is not a bug. Should you wish to continue this as a discussion, please feel free to reach out to me on Discord.

**Closed as completed by Ridanisaurus** 2022-11-29 10:24 UTC
Labels: bug, wontfix
