### ISSUE TITLE
[1.19.2] [Forge] [2.1.6] Registry Object not present: emendatusenigmatica:enigmatic_hammer

### ISSUE THREAD

**Issue by BelgianDev** [Ridanisaurus/EmendatusEnigmatica#217] opened 2024-02-04 13:38 UTC
### Issue description

The game crashes at startup caused by a NullPointerException (java.lang.NullPointerException: Registry Object not present: emendatusenigmatica:enigmatic_hammer)

Seems to be the same issue of #202 but on version 2.1.6 

### Steps to reproduce

- Install Emendatus version 2.1.6
- Launch Game
- Crash

### Minecraft version

1.19.2 (Latest)

### Forge version

43.3.0

### Emendatus Enigmatica version

2.1.x (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Raft08/2cf8c2ed3f8d0690951ab99ac9676857

**Comment by Ridanisaurus** [comment] 2024-02-05 07:25
Duplicate of #202

**Closed as completed by Ridanisaurus** 2024-02-05 07:25 UTC
Labels: bug, to be reviewed
