### ISSUE TITLE
Enigmatic Hammer Doesn't Work For Certain Recipes [1.16.5]

### ISSUE THREAD

**Issue by HockeyZman2000** [Ridanisaurus/EmendatusEnigmatica#119] opened 2021-11-09 19:14 UTC
**Mod Version**
1.2.13-build.3

**Describe the bug/enhancement**
Hammering down certain ingots into plates with the Enigmatic Hammer only works half of the time. Specifically the hammer works for every recipe until it is damaged , then it only works on certain ingots. When damaged, the only ingots that still work are:

Cobalt, Lumium, Cast Iron, Enderium, Brass, Constantan, Electrum, Invar, Signalum, and vanilla ingots.

Attempting to use the hammer after the first use on ingots other than these will result in the recipe not working. JEI shows that the recipe is valid, but it isn't valid after the hammer is damaged.

**To Reproduce - if applicable**
1. Damage an enigmatic hammer.
2. Attempt to put the hammer in the crafting grid with an ingot NOT listed above.
3. Admire that there is no output 

**Expected behavior**
I want all the plates

**Screenshots**
Using a Copper Ingot as an example:
![2021-11-09_13 13 16](https://user-images.githubusercontent.com/73307858/140989538-11db4efc-eae4-4b5d-a9ee-ae8a8ae46e27.png)
![2021-11-09_13 13 34](https://user-images.githubusercontent.com/73307858/140989551-f7b8ad68-c399-4eeb-9e64-7631d87c6f20.png)

**Comment by Ridanisaurus** [comment] 2021-11-10 07:56
Could you please confirm whether this is in a modpack, and if so, could you please provide me with a Modlist. I'm unable to replicate it with just EE.

**Comment by HockeyZman2000** [comment] 2021-11-10 18:35
It's in my custom private modpack. Sorry for the long list it takes a while to load. Just removed my KubeJS scripts to see if that had anything to do with it and it still happens. Hopefully you have some insight as to what's going on.

Modpack Link: https://drive.google.com/file/d/1m4S6DPM23ZcD02umzlPecKwzwSVeQ8nJ/view?usp=sharing

**Comment by Ridanisaurus** [comment] 2021-11-11 10:46
Instead of the Modpack itself, could you please just provide me with a modlist.

**Comment by Ridanisaurus** [comment] 2021-11-14 14:49
Do you have KubeJS in your modpack? If so, then this is the cause of it. Latvian is aware of the issue, and they are looking into it.
I will proceed to close this item as it's not related to Emendatus Enigmatica itself.

**Closed as completed by Ridanisaurus** 2021-11-14 14:49 UTC
Labels: bug
